---
title: "Activity: Nuclear Reactors"
author: "DEEKSHITH REDDY BHOOMIREDDY"
output: html_notebook
---

```{r}
library(tidyverse)
library(rvest)
library(dplyr)
library(lubridate)
```

## Scrape the Data 

```{r}


page <- "https://en.wikipedia.org/wiki/List_of_commercial_nuclear_reactors"

# Extracting all tables
SetOfTables <- 
  page %>%
  read_html() %>%
  html_nodes(css = "table") %>%
  html_table(fill = TRUE)


Japan <- SetOfTables[[21]]

# you may want to do your own investigation to understand why this line is needed
names(Japan)[c(3,7)] <- c("type", "grossMW")


Japan_cleaned <-
  Japan %>%
  filter(row_number() > 1) %>%
  rename(name = Plantname, 
         reactor = UnitNo.,
         model = Model,
         status = Status, 
         netMW = `Capacity(MW)`,
         construction = grossMW,
         operation = Commercialoperation, 
         closure = Closed) %>%
  mutate(
    netMW = as.numeric(netMW),
    reactor = gsub(",", "", reactor),
    construction = dmy(gsub("\\[.*?\\]", "", construction)),
    operation = dmy(gsub("\\[.*?\\]", "", operation)),
    closure = dmy(closure),
    country = "Japan"
    )

```


## Your turn: In what ways is the table tidy? How is it not tidy? What’s different about it from a tidy table?

My answer here..... 


## Your Turn: Plot Net Generation Capacity vs Construction Date

```{r}
ggplot(Japan_cleaned, aes(x = netMW, y = construction, color = reactor)) +
  geom_point() +
  labs(title = "Net Generation Capacity vs Date Of Construction", x = "Net generation capacity", y = "Date of construction", color = "Type of reactor")

```


## Your Turn: Scrape & Clean China Data (then merge with Japan)

```{r}
#my code here...
China <- SetOfTables[[10]]

# you may want to do your own investigation to understand why this line is needed
names(China)[c(3,7)] <- c("type", "grossMW")


China_cleaned <-
  China %>%
  filter(row_number() > 1) %>%
  rename(name = Plantname, 
         reactor = UnitNo.,
         model = Model,
         status = Status, 
         netMW = `Capacity(MW)`,
         construction = grossMW,
         operation = Commercialoperation, 
         closure = Closed) %>%
  mutate(
    netMW = as.numeric(netMW),
    name = gsub("\\[.*?\\]", "", name),
    construction = dmy(gsub("\\[.*?\\]", "", construction)),
    operation = dmy(gsub("\\[.*?\\]", "", operation)),
    closure = dmy(closure),
    country = "China"
    )

Combined_data <- bind_rows(Japan_cleaned, China_cleaned)

```



## Your Turn: Reconstruct Info Graphic of Japan Reactors (or other country of interest)

```{r}
#My code here

Japan_cleaned_for_graph <-
  Japan %>%
  rename(name = Plantname, 
         reactor = UnitNo.,
         model = Model,
         status = Status, 
         netMW = `Capacity(MW)`,
         construction = grossMW,
         operation = Commercialoperation, 
         closure = Closed) %>%
  mutate(
    netMW = as.numeric(netMW),
    reactor = gsub(",", "", reactor),
    construction = dmy(gsub("\\[.*?\\]", "", construction)),
    operation = dmy(gsub("\\[.*?\\]", "", operation)),
    closure = dmy(closure),
    country = "Japan",
    reactorID = paste(name, reactor, sep = " ")
    )

Japan_minimized <- 
  Japan_cleaned_for_graph %>% 
  slice(1:32) %>%
  arrange(desc(reactorID))

Japan_minimized %>%
  ggplot(aes(y = reactorID, x = construction, xend = operation, yend = reactorID)) +
  geom_segment(aes(color = type), size = 3) +
  labs(x = "operation",
    y = "reactorID",
    color = "type"
  )

```